# Generated by Django 4.1.2 on 2022-11-03 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=18, unique=True, verbose_name='discord id')),
                ('name', models.CharField(max_length=100, verbose_name='author name')),
                ('discriminator', models.CharField(max_length=4, verbose_name='discriminator')),
                ('avatar_url', models.CharField(max_length=100, verbose_name='avatar url')),
                ('color', models.CharField(max_length=7, verbose_name='name color')),
                ('is_bot', models.BooleanField(default=False, verbose_name='is a bot')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=18, unique=True, verbose_name='discord id')),
                ('name', models.CharField(max_length=100, verbose_name='channel name')),
                ('topic', models.TextField(verbose_name='channel topic')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord_messages.category', to_field='discord_id')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=18, unique=True, verbose_name='discord id')),
                ('name', models.CharField(max_length=100, verbose_name='server name')),
                ('icon_url', models.CharField(max_length=100, verbose_name='icon url')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=18, unique=True, verbose_name='discord id')),
                ('timestamp_sent', models.DateTimeField(verbose_name='timestamp sent')),
                ('timestamp_edited', models.DateTimeField(blank=True, default=None, verbose_name='timestamp edited')),
                ('content', models.TextField(verbose_name='content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discord_messages.author', to_field='discord_id')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discord_messages.channel', to_field='discord_id')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord_messages.guild'),
        ),
        migrations.AddField(
            model_name='category',
            name='guild_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='discord_messages.guild', to_field='discord_id'),
        ),
    ]
