# Generated by Django 4.1.2 on 2022-11-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='guild_id',
            new_name='guild',
        ),
    ]
