# Generated by Django 4.1.2 on 2022-11-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_messages", "0002_rename_guild_id_category_guild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="category name"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="icon_url",
            field=models.CharField(max_length=255, verbose_name="icon url"),
        ),
        migrations.AlterField(
            model_name="guild",
            name="name",
            field=models.CharField(max_length=255, verbose_name="server name"),
        ),
    ]
