# Generated by Django 4.1.2 on 2022-11-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_messages", "0003_alter_category_name_alter_guild_icon_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="avatar_url",
            field=models.CharField(max_length=255, verbose_name="avatar url"),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, verbose_name="author name"),
        ),
    ]
