# Generated by Django 4.1.2 on 2022-11-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_messages", "0004_alter_author_avatar_url_alter_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="discord_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="discord id"
            ),
        ),
    ]
