# Generated by Django 4.1.2 on 2022-11-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_messages", "0005_alter_message_discord_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestamp_edited",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="timestamp edited"
            ),
        ),
    ]
